# -*- coding: utf-8 -*-
"""Project 107

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dnUojM3qKOTq1b7nAZjKCWksVsh6Nc7h
"""

from google.colab import files
data = files.upload()

import pandas as pd
import csv
import plotly.express as px

df = pd.read_csv("Average Distance traveled in sports.csv")
fig = px.bar(df, x = "Sport", y = "Distance(Km)")
fig.show()